// Validation against the frozen Python reference table (tests/refdata/core.json,
// generated by tests/gen_ref_tables.py).
//
// Sections whose Python implementation is pure IEEE arithmetic, exact rational
// arithmetic, MT19937, or formatting are compared bit-for-bit (a == b).
//
// Sections that transit through libm transcendentals are compared with
// tolerance instead, and bit equality there is not a well-defined target:
// CPython delegates math.log / math.erf to the platform C runtime, and UCRT
// (Windows), glibc, and Go's fdlibm port each round differently — a probe of
// ~8000 inputs shows UCRT's log and erf deviate from the correctly-rounded
// value by 1-2 ulp on roughly a quarter of inputs. The tolerances follow the
// error structure:
//
//   - normInvCDF / zTwoSided: log feeds sqrt and a polynomial; its 1-2 ulp
//     error arrives as <= a few ulp of the final quantile → fewUlpEq.
//   - tail p-values (two_prop, compare): p = 2*(1 - cdf) = 1 - erf(w), where
//     the subtraction is exact, so an erf error of a few ulp at magnitude <= 1
//     becomes an ABSOLUTE error <= ~1e-15 regardless of how small p is →
//     pValueEq combines that absolute floor with the relative tolerance.
package evalsig

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"sync"
	"testing"
)

const refdataPath = "../../tests/refdata/core.json"

type section struct {
	Mode  string `json:"mode"`
	Cases []json.RawMessage `json:"cases"`
}

var (
	refOnce sync.Once
	refTab  map[string]section
	refErr  error
)

func sections(t *testing.T) map[string]section {
	t.Helper()
	refOnce.Do(func() {
		data, err := os.ReadFile(refdataPath)
		if err != nil {
			refErr = fmt.Errorf("reference table not found: %v (run tests/gen_ref_tables.py)", err)
			return
		}
		if err := json.Unmarshal(data, &refTab); err != nil {
			refErr = fmt.Errorf("bad reference table: %v", err)
		}
	})
	if refErr != nil {
		t.Skipf("%v", refErr)
	}
	return refTab
}

func casesOf(t *testing.T, name string) []json.RawMessage {
	t.Helper()
	s, ok := sections(t)[name]
	if !ok {
		t.Fatalf("section %q missing from reference table", name)
	}
	return s.Cases
}

// flex decodes a float that may carry the "nan"/"inf"/"-inf" markers.
type flex float64

func (f *flex) UnmarshalJSON(b []byte) error {
	switch string(b) {
	case `"nan"`:
		*f = flex(math.NaN())
		return nil
	case `"inf"`:
		*f = flex(math.Inf(1))
		return nil
	case `"-inf"`:
		*f = flex(math.Inf(-1))
		return nil
	}
	var v float64
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	*f = flex(v)
	return nil
}

func bitsEq(a, b float64) bool {
	if math.IsNaN(a) || math.IsNaN(b) {
		return math.IsNaN(a) && math.IsNaN(b)
	}
	return a == b
}

// fewUlpEq: relative tolerance covering a handful of ulp of libm divergence.
func fewUlpEq(a, b float64) bool {
	if bitsEq(a, b) {
		return true
	}
	if math.IsNaN(a) || math.IsNaN(b) || math.IsInf(a, 0) || math.IsInf(b, 0) {
		return false
	}
	if b == 0 {
		return math.Abs(a) < 1e-300
	}
	return math.Abs(a-b)/math.Abs(b) < 4e-15
}

// pValueEq: tail p-values are 2*(1-cdf), so an erf/betainc error of a few ulp
// at magnitude ~1 lands as an absolute error <= ~1e-15 in p regardless of how
// small p itself is. Observed divergences: 1-2 ulp of the intermediate cdf
// (2.2e-16 and 4.4e-16 in two_prop / compare), matching the model.
func pValueEq(a, b float64) bool {
	if bitsEq(a, b) {
		return true
	}
	if math.IsNaN(a) || math.IsNaN(b) {
		return false
	}
	d := math.Abs(a - b)
	return d <= 1e-15 || d/math.Abs(b) < 4e-15
}

func fdesc(v float64) string { return pyReprFloat(v) }

func failFloat(t *testing.T, ctx string, got, want float64, ulp bool) {
	t.Helper()
	kind := "bits"
	if ulp {
		kind = "ulp"
	}
	t.Errorf("%s: got %s, want %s (%s)", ctx, fdesc(got), fdesc(want), kind)
}

// ---------------------------------------------------------------- z / normal

func TestRefZTwoSided(t *testing.T) {
	var cases []struct {
		Alpha float64 `json:"alpha"`
		Want  float64 `json:"want"`
	}
	mustDecode(t, casesOf(t, "z_two_sided"), &cases)
	for i, c := range cases {
		if got := zTwoSided(c.Alpha); !fewUlpEq(got, c.Want) {
			failFloat(t, fmt.Sprintf("z_two_sided[%d] alpha=%v", i, c.Alpha), got, c.Want, true)
		}
	}
}

func TestRefNormInvCDF(t *testing.T) {
	var cases []struct {
		P    float64 `json:"p"`
		Want float64 `json:"want"`
	}
	mustDecode(t, casesOf(t, "norm_inv_cdf"), &cases)
	for i, c := range cases {
		if got := normInvCDF(c.P); !fewUlpEq(got, c.Want) {
			failFloat(t, fmt.Sprintf("normInvCDF[%d] p=%v", i, c.P), got, c.Want, true)
		}
	}
}

func TestRefNormCDF(t *testing.T) {
	var cases []struct {
		X    float64 `json:"x"`
		Want float64 `json:"want"`
	}
	mustDecode(t, casesOf(t, "norm_cdf"), &cases)
	for i, c := range cases {
		if got := normCDF(c.X); !fewUlpEq(got, c.Want) {
			failFloat(t, fmt.Sprintf("normCDF[%d] x=%v", i, c.X), got, c.Want, true)
		}
	}
}

// ---------------------------------------------------------------- intervals

func TestRefWilson(t *testing.T) {
	var cases []struct {
		S        int     `json:"s"`
		N        int     `json:"n"`
		Alpha    float64 `json:"alpha"`
		Low      float64 `json:"low"`
		High     float64 `json:"high"`
		RootsLow float64 `json:"roots_low"`
		RootsHigh float64 `json:"roots_high"`
	}
	mustDecode(t, casesOf(t, "wilson"), &cases)
	for i, c := range cases {
		w := WilsonInterval(c.S, c.N, c.Alpha)
		if !bitsEq(w.Low, c.Low) || !bitsEq(w.High, c.High) {
			failFloat(t, fmt.Sprintf("wilson[%d] %d/%d a=%v low", i, c.S, c.N, c.Alpha), w.Low, c.Low, false)
			failFloat(t, fmt.Sprintf("wilson[%d] %d/%d a=%v high", i, c.S, c.N, c.Alpha), w.High, c.High, false)
		}
		r := WilsonIntervalRoots(c.S, c.N, c.Alpha)
		if !bitsEq(r.Low, c.RootsLow) || !bitsEq(r.High, c.RootsHigh) {
			failFloat(t, fmt.Sprintf("wilsonRoots[%d] %d/%d a=%v low", i, c.S, c.N, c.Alpha), r.Low, c.RootsLow, false)
			failFloat(t, fmt.Sprintf("wilsonRoots[%d] %d/%d a=%v high", i, c.S, c.N, c.Alpha), r.High, c.RootsHigh, false)
		}
	}
}

func TestRefNewcombe(t *testing.T) {
	var cases []struct {
		P1    float64 `json:"p1"`
		N1    int     `json:"n1"`
		P2    float64 `json:"p2"`
		N2    int     `json:"n2"`
		Alpha float64 `json:"alpha"`
		Low   float64 `json:"low"`
		High  float64 `json:"high"`
	}
	mustDecode(t, casesOf(t, "newcombe"), &cases)
	for i, c := range cases {
		got := NewcombeDiffInterval(c.P1, c.N1, c.P2, c.N2, c.Alpha)
		if !bitsEq(got.Low, c.Low) || !bitsEq(got.High, c.High) {
			failFloat(t, fmt.Sprintf("newcombe[%d]", i), got.Low, c.Low, false)
			failFloat(t, fmt.Sprintf("newcombe[%d]", i), got.High, c.High, false)
		}
	}
}

func TestRefTwoProportion(t *testing.T) {
	var cases []struct {
		S1    int   `json:"s1"`
		N1    int   `json:"n1"`
		S2    int   `json:"s2"`
		N2    int   `json:"n2"`
		Alpha float64 `json:"alpha"`
		Diff  float64 `json:"diff"`
		Low   float64 `json:"low"`
		High  float64 `json:"high"`
		Z     flex   `json:"z"`
		P     flex   `json:"p"`
	}
	mustDecode(t, casesOf(t, "two_prop"), &cases)
	for i, c := range cases {
		r := TwoProportionTest(c.S1, c.N1, c.S2, c.N2, c.Alpha)
		if !bitsEq(r.Diff, c.Diff) {
			failFloat(t, fmt.Sprintf("twoProp[%d] diff", i), r.Diff, c.Diff, false)
		}
		if !bitsEq(r.CI.Low, c.Low) || !bitsEq(r.CI.High, c.High) {
			failFloat(t, fmt.Sprintf("twoProp[%d] ci.low", i), r.CI.Low, c.Low, false)
			failFloat(t, fmt.Sprintf("twoProp[%d] ci.high", i), r.CI.High, c.High, false)
		}
		if !bitsEq(float64(c.Z), r.Z) {
			failFloat(t, fmt.Sprintf("twoProp[%d] z", i), r.Z, float64(c.Z), false)
		}
		if !pValueEq(r.PValue, float64(c.P)) {
			failFloat(t, fmt.Sprintf("twoProp[%d] p", i), r.PValue, float64(c.P), true)
		}
	}
}

func TestRefBinomCDF(t *testing.T) {
	var cases []struct {
		K    int     `json:"k"`
		N    int     `json:"n"`
		P    float64 `json:"p"`
		Want float64 `json:"want"`
	}
	mustDecode(t, casesOf(t, "binom_cdf"), &cases)
	for i, c := range cases {
		if got := BinomCDF(c.K, c.N, c.P); !bitsEq(got, c.Want) {
			failFloat(t, fmt.Sprintf("BinomCDF[%d] k=%d n=%d p=%v", i, c.K, c.N, c.P), got, c.Want, false)
		}
	}
}

func TestRefMcNemar(t *testing.T) {
	var cases []struct {
		B     int     `json:"b"`
		C     int     `json:"c"`
		Alpha float64 `json:"alpha"`
		Diff  float64 `json:"diff"`
		Low   float64 `json:"low"`
		High  float64 `json:"high"`
		P     float64 `json:"p"`
	}
	mustDecode(t, casesOf(t, "mcnemar"), &cases)
	for i, c := range cases {
		m := McNemarExact(c.B, c.C, c.Alpha)
		if !bitsEq(m.Diff, c.Diff) || !bitsEq(m.PValue, c.P) {
			failFloat(t, fmt.Sprintf("mcnemar[%d] b=%d c=%d diff", i, c.B, c.C), m.Diff, c.Diff, false)
			failFloat(t, fmt.Sprintf("mcnemar[%d] b=%d c=%d p", i, c.B, c.C), m.PValue, c.P, false)
		}
		if !bitsEq(m.CI.Low, c.Low) || !bitsEq(m.CI.High, c.High) {
			failFloat(t, fmt.Sprintf("mcnemar[%d] b=%d c=%d low", i, c.B, c.C), m.CI.Low, c.Low, false)
			failFloat(t, fmt.Sprintf("mcnemar[%d] b=%d c=%d high", i, c.B, c.C), m.CI.High, c.High, false)
		}
	}
}

func TestRefClusterBootstrap(t *testing.T) {
	var cases []struct {
		Clusters [][]float64 `json:"clusters"`
		B        int         `json:"B"`
		Alpha    float64     `json:"alpha"`
		Seed     int         `json:"seed"`
		Low      float64     `json:"low"`
		High     float64     `json:"high"`
	}
	mustDecode(t, casesOf(t, "cluster_bootstrap"), &cases)
	for i, c := range cases {
		ci := ClusterBootstrapCI(c.Clusters, nil, c.B, c.Alpha, c.Seed)
		if !bitsEq(ci.Low, c.Low) || !bitsEq(ci.High, c.High) {
			failFloat(t, fmt.Sprintf("bootstrap[%d] k=%d B=%d seed=%d low", i, len(c.Clusters), c.B, c.Seed), ci.Low, c.Low, false)
			failFloat(t, fmt.Sprintf("bootstrap[%d] k=%d B=%d seed=%d high", i, len(c.Clusters), c.B, c.Seed), ci.High, c.High, false)
		}
	}
}

// ---------------------------------------------------------------- exact mean / stdev

func TestRefMeanStdev(t *testing.T) {
	var cases []struct {
		Vals  []float64 `json:"vals"`
		Mean  float64   `json:"mean"`
		Stdev *float64  `json:"stdev"`
	}
	mustDecode(t, casesOf(t, "mean_stdev"), &cases)
	for i, c := range cases {
		if got := exactMean(c.Vals); !bitsEq(got, c.Mean) {
			failFloat(t, fmt.Sprintf("mean[%d] n=%d", i, len(c.Vals)), got, c.Mean, false)
		}
		if c.Stdev != nil {
			if got := exactStdev(c.Vals); !bitsEq(got, *c.Stdev) {
				failFloat(t, fmt.Sprintf("stdev[%d] n=%d", i, len(c.Vals)), got, *c.Stdev, false)
			}
		}
	}
}

// ---------------------------------------------------------------- power

func TestRefPower(t *testing.T) {
	var cases []struct {
		Kind  string  `json:"kind"`
		P1    float64 `json:"p1"`
		P2    float64 `json:"p2"`
		Disc  float64 `json:"disc"`
		Delta float64 `json:"delta"`
		Width float64 `json:"width"`
		P     float64 `json:"p"`
		Alpha float64 `json:"alpha"`
		Power float64 `json:"power"`
		N     int     `json:"n"`
	}
	mustDecode(t, casesOf(t, "power"), &cases)
	for i, c := range cases {
		var got int
		switch c.Kind {
		case "two":
			got = NTwoProportions(c.P1, c.P2, c.Alpha, c.Power).NPerVersion
		case "paired":
			got = NPaired(c.Disc, c.Delta, c.Alpha, c.Power).NPerVersion
		case "width":
			got = NForCIWidth(c.Width, c.P, c.Alpha).NPerVersion
		default:
			t.Fatalf("power[%d]: unknown kind %q", i, c.Kind)
		}
		if got != c.N {
			t.Errorf("power[%d] %s: got n=%d, want %d", i, c.Kind, got, c.N)
		}
	}
}

// ---------------------------------------------------------------- variance

func TestRefVarianceComponents(t *testing.T) {
	var cases []struct {
		Groups  [][]json.RawMessage `json:"groups"`
		Between float64             `json:"between"`
		Within  float64             `json:"within"`
		Total   float64             `json:"total"`
		ICC     float64             `json:"icc"`
	}
	mustDecode(t, casesOf(t, "variance_components"), &cases)
	for i, c := range cases {
		groups := make([]*group, 0, len(c.Groups))
		for _, g := range c.Groups {
			var name string
			var vals []float64
			if err := json.Unmarshal(g[0], &name); err != nil {
				t.Fatalf("variance[%d]: bad group name: %v", i, err)
			}
			if err := json.Unmarshal(g[1], &vals); err != nil {
				t.Fatalf("variance[%d]: bad group values: %v", i, err)
			}
			groups = append(groups, &group{key: name, vals: vals})
		}
		vc := VarianceComponentsOf(groups)
		if !bitsEq(vc.Between, c.Between) || !bitsEq(vc.Within, c.Within) ||
			!bitsEq(vc.Total, c.Total) || !bitsEq(vc.ICC, c.ICC) {
			failFloat(t, fmt.Sprintf("variance[%d] between", i), vc.Between, c.Between, false)
			failFloat(t, fmt.Sprintf("variance[%d] within", i), vc.Within, c.Within, false)
			failFloat(t, fmt.Sprintf("variance[%d] total", i), vc.Total, c.Total, false)
			failFloat(t, fmt.Sprintf("variance[%d] icc", i), vc.ICC, c.ICC, false)
		}
	}
}

// ---------------------------------------------------------------- holm

func TestRefHolm(t *testing.T) {
	var cases []struct {
		Alpha   float64          `json:"alpha"`
		Entries [][2]interface{} `json:"entries"`
		Want    [][3]interface{} `json:"want"`
	}
	mustDecode(t, casesOf(t, "holm"), &cases)
	for i, c := range cases {
		in := make([]HolmP, 0, len(c.Entries))
		for _, e := range c.Entries {
			in = append(in, HolmP{Name: toString(e[0]), P: toFloat(t, e[1])})
		}
		got := Holm(in, c.Alpha)
		if len(got) != len(c.Want) {
			t.Fatalf("holm[%d]: got %d entries, want %d", i, len(got), len(c.Want))
		}
		for j, w := range c.Want {
			if got[j].Name != toString(w[0]) {
				t.Errorf("holm[%d][%d]: name got %q want %q", i, j, got[j].Name, toString(w[0]))
			}
			if !bitsEq(got[j].Adjusted, toFloat(t, w[1])) {
				failFloat(t, fmt.Sprintf("holm[%d][%d] adj", i, j), got[j].Adjusted, toFloat(t, w[1]), false)
			}
			if got[j].Reject != toBool(w[2]) {
				t.Errorf("holm[%d][%d]: reject got %v want %v", i, j, got[j].Reject, toBool(w[2]))
			}
		}
	}
}

func toString(v interface{}) string {
	if s, ok := v.(string); ok {
		return s
	}
	return fmt.Sprintf("%v", v)
}

func toFloat(t *testing.T, v interface{}) float64 {
	t.Helper()
	switch x := v.(type) {
	case float64:
		return x
	case int:
		return float64(x)
	case json.Number:
		f, err := x.Float64()
		if err != nil {
			t.Fatalf("bad number %v", x)
		}
		return f
	}
	t.Fatalf("expected number, got %T", v)
	return 0
}

func toBool(v interface{}) bool {
	b, ok := v.(bool)
	if !ok {
		return false
	}
	return b
}

// ---------------------------------------------------------------- MT19937

func TestRefMT19937(t *testing.T) {
	var cases []struct {
		Seed int      `json:"seed"`
		Kind string   `json:"kind"`
		K    int      `json:"k"`
		Want []uint64 `json:"want"`
	}
	mustDecode(t, casesOf(t, "mt19937"), &cases)
	for i, c := range cases {
		r := &pyRandom{}
		r.seedInt(int64(c.Seed))
		var draw func() uint64
		switch {
		case c.Kind == "randrange":
			draw = nil // handled below: randrange consumes _randbelow words
		case c.Kind == "getrandbits32":
			draw = func() uint64 { return r.getrandbits(32) }
		default:
			var bits int
			if _, err := fmt.Sscanf(c.Kind, "getrandbits%d", &bits); err != nil {
				t.Fatalf("mt[%d]: bad kind %q", i, c.Kind)
			}
			draw = func() uint64 { return r.getrandbits(bits) }
		}
		got := make([]uint64, 0, len(c.Want))
		if draw == nil {
			for j := 0; j < len(c.Want); j++ {
				got = append(got, uint64(r.randrange(c.K)))
			}
		} else {
			for j := 0; j < len(c.Want); j++ {
				got = append(got, draw())
			}
		}
		if len(got) != len(c.Want) {
			t.Fatalf("mt[%d]: length %d != %d", i, len(got), len(c.Want))
		}
		for j := range got {
			if got[j] != c.Want[j] {
				t.Errorf("mt[%d] %s seed=%d [%d]: got %d, want %d", i, c.Kind, c.Seed, j, got[j], c.Want[j])
			}
		}
	}
}

// ---------------------------------------------------------------- rounding & formatting

func TestRefPyRound(t *testing.T) {
	var cases []struct {
		X    float64 `json:"x"`
		Want int64   `json:"want"`
	}
	mustDecode(t, casesOf(t, "py_round"), &cases)
	for i, c := range cases {
		if got := pyRound(c.X); got != c.Want {
			t.Errorf("pyRound[%d] x=%s: got %d, want %d", i, fdesc(c.X), got, c.Want)
		}
	}
}

func TestRefFmtG4(t *testing.T) {
	var cases []struct {
		X    float64 `json:"x"`
		Want string  `json:"want"`
	}
	mustDecode(t, casesOf(t, "fmt_g4"), &cases)
	for i, c := range cases {
		if got := pyFormatG(c.X, 4); got != c.Want {
			t.Errorf("fmtG4[%d] x=%s: got %q, want %q", i, fdesc(c.X), got, c.Want)
		}
	}
}

func TestRefFmtF4(t *testing.T) {
	var cases []struct {
		X    float64 `json:"x"`
		Want string  `json:"want"`
	}
	mustDecode(t, casesOf(t, "fmt_f4"), &cases)
	for i, c := range cases {
		if got := pyFormatF(c.X, 4); got != c.Want {
			t.Errorf("fmtF4[%d] x=%s: got %q, want %q", i, fdesc(c.X), got, c.Want)
		}
	}
}

func TestRefFmtPct(t *testing.T) {
	var cases []struct {
		X    float64 `json:"x"`
		Want string  `json:"want"`
	}
	mustDecode(t, casesOf(t, "fmt_pct"), &cases)
	for i, c := range cases {
		if got := pyPercent0(c.X); got != c.Want {
			t.Errorf("fmtPct[%d] x=%s: got %q, want %q", i, fdesc(c.X), got, c.Want)
		}
	}
}

func TestRefPyRepr(t *testing.T) {
	var cases []struct {
		X    float64 `json:"x"`
		Want string  `json:"want"`
	}
	mustDecode(t, casesOf(t, "py_repr"), &cases)
	for i, c := range cases {
		if got := pyReprFloat(c.X); got != c.Want {
			t.Errorf("repr[%d]: got %q, want %q", i, got, c.Want)
		}
	}
}

// ---------------------------------------------------------------- json.dumps

func TestRefJSONDumps(t *testing.T) {
	var cases []struct {
		Value json.RawMessage `json:"value"`
		Want  string          `json:"want"`
	}
	mustDecode(t, casesOf(t, "json_dumps"), &cases)
	for i, c := range cases {
		v, err := parsePyJSON([]byte(c.Value))
		if err != nil {
			t.Fatalf("jsonDumps[%d]: parse: %v", i, err)
		}
		if got := pyJSONDumps(v); got != c.Want {
			t.Errorf("jsonDumps[%d]:\ngot  %q\nwant %q", i, got, c.Want)
		}
	}
}

// ---------------------------------------------------------------- compare (end to end)

func TestRefCompare(t *testing.T) {
	type want struct {
		Estimate flex   `json:"estimate"`
		Low      flex   `json:"low"`
		High     flex   `json:"high"`
		P        flex   `json:"p"`
		Method   string `json:"method"`
		Paired   bool   `json:"paired"`
		Verdict  string `json:"verdict"`
		Needed   int    `json:"additional_needed"`
	}
	var cases []struct {
		Name  string          `json:"name"`
		Alpha float64         `json:"alpha"`
		RunsA json.RawMessage `json:"runs_a"`
		RunsB json.RawMessage `json:"runs_b"`
		Want  want            `json:"want"`
	}
	mustDecode(t, casesOf(t, "compare"), &cases)
	for i, c := range cases {
		ra, err := runsFromRaw(c.RunsA)
		if err != nil {
			t.Fatalf("compare[%d]: %v", i, err)
		}
		rb, err := runsFromRaw(c.RunsB)
		if err != nil {
			t.Fatalf("compare[%d]: %v", i, err)
		}
		got, err := Compare(ra, rb, "A", "B", c.Alpha)
		if err != nil {
			t.Fatalf("compare[%d]: %v", i, err)
		}
		w := c.Want
		if !bitsEq(got.Estimate, float64(w.Estimate)) {
			failFloat(t, fmt.Sprintf("compare[%d] %s estimate", i, c.Name), got.Estimate, float64(w.Estimate), false)
		}
		if !bitsEq(got.CI.Low, float64(w.Low)) || !bitsEq(got.CI.High, float64(w.High)) {
			failFloat(t, fmt.Sprintf("compare[%d] %s ci.low", i, c.Name), got.CI.Low, float64(w.Low), false)
			failFloat(t, fmt.Sprintf("compare[%d] %s ci.high", i, c.Name), got.CI.High, float64(w.High), false)
		}
		if !pValueEq(got.PValue, float64(w.P)) {
			failFloat(t, fmt.Sprintf("compare[%d] %s p", i, c.Name), got.PValue, float64(w.P), true)
		}
		if got.Method != w.Method || got.Paired != w.Paired || got.Verdict != w.Verdict || got.AdditionalNeeded != w.Needed {
			t.Errorf("compare[%d] %s: method=%q paired=%v verdict=%q needed=%d; want %q %v %q %d",
				i, c.Name, got.Method, got.Paired, got.Verdict, got.AdditionalNeeded,
				w.Method, w.Paired, w.Verdict, w.Needed)
		}
	}
}

func runsFromRaw(raw json.RawMessage) ([]Run, error) {
	v, err := parsePyJSON([]byte(raw))
	if err != nil {
		return nil, err
	}
	arr, ok := v.([]interface{})
	if !ok {
		return nil, fmt.Errorf("expected array")
	}
	return runsFromArray(arr, "")
}

// ---------------------------------------------------------------- decide (end to end)

func TestRefDecide(t *testing.T) {
	var cases []struct {
		Candidates   json.RawMessage `json:"candidates"`
		Alpha        float64         `json:"alpha"`
		WantRanking  [][]interface{} `json:"want_ranking"`
		WantAdjusted [][2]interface{} `json:"want_adjusted"`
		WantVerdicts []string        `json:"want_verdicts"`
		WantMethods  []string        `json:"want_methods"`
	}
	mustDecode(t, casesOf(t, "decide"), &cases)
	for i, c := range cases {
		v, err := parsePyJSON([]byte(c.Candidates))
		if err != nil {
			t.Fatalf("decide[%d]: parse: %v", i, err)
		}
		obj, ok := v.(*pyObj)
		if !ok {
			t.Fatalf("decide[%d]: candidates not an object", i)
		}
		var cands []Candidate
		for _, kv := range obj.pairs {
			arr, ok := kv.v.([]interface{})
			if !ok {
				t.Fatalf("decide[%d]: candidate %q runs not an array", i, kv.k)
			}
			runs, err := runsFromArray(arr, "")
			if err != nil {
				t.Fatalf("decide[%d]: %v", i, err)
			}
			cands = append(cands, Candidate{Name: kv.k, Runs: runs})
		}
		rep, err := Decide(cands, c.Alpha)
		if err != nil {
			t.Fatalf("decide[%d]: %v", i, err)
		}
		for j, w := range c.WantRanking {
			name := toString(w[0])
			if rep.Ranking[j].Name != name {
				t.Errorf("decide[%d] ranking[%d]: name got %q want %q", i, j, rep.Ranking[j].Name, name)
			}
			if !bitsEq(rep.Ranking[j].Estimate, toFloat(t, w[1])) {
				failFloat(t, fmt.Sprintf("decide[%d] ranking[%d] %s est", i, j, name),
					rep.Ranking[j].Estimate, toFloat(t, w[1]), false)
			}
			if rep.Ranking[j].Action != toString(w[2]) {
				t.Errorf("decide[%d] ranking[%d] %s: action got %q want %q", i, j, name,
					rep.Ranking[j].Action, toString(w[2]))
			}
		}
		for j, w := range c.WantAdjusted {
			// w[1] is Python's repr of the adjusted p — compare via repr
			if rep.Adjusted[j].Name != toString(w[0]) || pyReprFloat(rep.Adjusted[j].Adjusted) != toString(w[1]) {
				t.Errorf("decide[%d] adjusted[%d]: got %q %s, want %q %s", i, j,
					rep.Adjusted[j].Name, pyReprFloat(rep.Adjusted[j].Adjusted), toString(w[0]), toString(w[1]))
			}
		}
		if len(rep.Comparisons) != len(c.WantVerdicts) {
			t.Fatalf("decide[%d]: %d comparisons, want %d", i, len(rep.Comparisons), len(c.WantVerdicts))
		}
		for j, cmp := range rep.Comparisons {
			if cmp.Verdict != c.WantVerdicts[j] || cmp.Method != c.WantMethods[j] {
				t.Errorf("decide[%d] comparison[%d]: verdict=%q method=%q; want %q %q",
					i, j, cmp.Verdict, cmp.Method, c.WantVerdicts[j], c.WantMethods[j])
			}
		}
	}
}

// ---------------------------------------------------------------- sequential

func TestRefSequential(t *testing.T) {
	var cases []struct {
		Kind      string       `json:"kind"`
		Alpha     float64      `json:"alpha"`
		Half      float64      `json:"half"`
		Steps     [][]float64  `json:"steps"`
		Verdicts  []string     `json:"verdicts"`
		LooksUsed int          `json:"looks_used"`
	}
	mustDecode(t, casesOf(t, "sequential"), &cases)
	for i, c := range cases {
		if len(c.Steps) != len(c.Verdicts) {
			t.Fatalf("sequential[%d]: steps/verdicts length mismatch", i)
		}
		if c.Kind == "prop" {
			sp := NewSequentialProportion(c.Alpha, c.Half)
			for j, st := range c.Steps {
				if got := sp.Update(int(st[0]), int(st[1])); got != c.Verdicts[j] {
					t.Errorf("sequential[%d] step %d: verdict got %q want %q", i, j, got, c.Verdicts[j])
				}
			}
			if sp.LooksUsed != c.LooksUsed {
				t.Errorf("sequential[%d]: looks_used got %d want %d", i, sp.LooksUsed, c.LooksUsed)
			}
		} else {
			ab := NewSequentialAB(c.Alpha, c.Half)
			for j, st := range c.Steps {
				if got := ab.Update(int(st[0]), int(st[1]), int(st[2]), int(st[3])); got != c.Verdicts[j] {
					t.Errorf("sequential[%d] step %d: verdict got %q want %q", i, j, got, c.Verdicts[j])
				}
			}
			if ab.LooksUsed != c.LooksUsed {
				t.Errorf("sequential[%d]: looks_used got %d want %d", i, ab.LooksUsed, c.LooksUsed)
			}
		}
	}
}

// ---------------------------------------------------------------- panic parity

// The Python reference raises StatisticsError when every cluster in a
// bootstrap resample is empty; the Go port panics with the same message. With
// k=2 clusters of which one is empty, a quarter of seeds hit the all-empty
// resample, so this pins the error path too.
func TestClusterBootstrapAllEmptyResamplePanics(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatalf("expected panic on all-empty resample")
		}
	}()
	clusters := [][]float64{{1.0, 2.0}, {}}
	ClusterBootstrapCI(clusters, nil, 4, 0.05, 0)
}

// The Python reference raises ValueError("n must be >= 1, ...") on zero sample
// size; the Go port panics with the same message instead of dividing to NaN.
func TestZeroNPanics(t *testing.T) {
	for _, tc := range []struct {
		name string
		fn   func()
	}{
		{"two_proportion n1=0", func() { TwoProportionTest(0, 0, 5, 10, 0.05) }},
		{"two_proportion n2=0", func() { TwoProportionTest(5, 10, 0, 0, 0.05) }},
		{"sequential update n=0", func() { NewSequentialProportion(0.05, 0.05).Update(0, 0) }},
	} {
		t.Run(tc.name, func(t *testing.T) {
			defer func() {
				r := recover()
				if r == nil {
					t.Fatalf("expected panic, got none")
				}
				if msg, ok := r.(string); ok && msg != "n must be >= 1, got 0" {
					t.Fatalf("panic message: got %q, want %q", msg, "n must be >= 1, got 0")
				}
			}()
			tc.fn()
		})
	}
}

func mustDecode(t *testing.T, raws []json.RawMessage, dst interface{}) {
	t.Helper()
	if err := json.Unmarshal(mustJoin(raws), dst); err != nil {
		t.Fatalf("decode reference cases: %v", err)
	}
}

func mustJoin(raws []json.RawMessage) []byte {
	var b bytes.Buffer
	b.WriteByte('[')
	for i, r := range raws {
		if i > 0 {
			b.WriteByte(',')
		}
		b.Write(r)
	}
	b.WriteByte(']')
	return b.Bytes()
}
