// test_refdata.cpp — validation against the frozen Python reference table
// (tests/refdata/core.json, generated by tests/gen_ref_tables.py).
//
// C++ port of internal/evalsig/refdata_test.go. Sections whose Python
// implementation is pure IEEE arithmetic, exact rational arithmetic, MT19937,
// or formatting are compared bit-for-bit (a == b). Sections that transit
// through libm transcendentals are compared with tolerance instead, and bit
// equality there is not a well-defined target: CPython delegates math.log /
// math.erf to the platform C runtime, and UCRT (Windows), glibc, and Go's
// fdlibm port each round differently. The tolerances follow the error
// structure:
//
//   - normInvCDF / zTwoSided: log feeds sqrt and a polynomial; its 1-2 ulp
//     error arrives as <= a few ulp of the final quantile -> fewUlpEq.
//   - tail p-values (two_prop, compare): p = 2*(1 - cdf) = 1 - erf(w), where
//     the subtraction is exact, so an erf error of a few ulp at magnitude <= 1
//     becomes an ABSOLUTE error <= ~1e-15 regardless of how small p is ->
//     pValueEq combines that absolute floor with the relative tolerance.

#include <cmath>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <functional>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#include "decide.h"
#include "intervals.h"
#include "power.h"
#include "pynum.h"
#include "pyjson.h"
#include "sequential.h"
#include "variance.h"
#include <stdexcept>
#include <cfloat>
#include <tuple>

using namespace evalsig;

namespace {

int g_failures = 0;
int g_sections = 0;

void fail(const std::string& msg) {
    if (g_failures < 60) {
        std::printf("--- FAIL: %s\n", msg.c_str());
    }
    g_failures++;
}

const std::string REFDATA_PATHS[] = {
    "../tests/refdata/core.json",  // run from cpp/
    "tests/refdata/core.json",     // run from the repo root
};

// ---------------------------------------------------------------- accessors

const PyValue& field(const PyObj& o, const std::string& k) {
    const PyValue* v = o.get(k);
    if (!v) throw std::runtime_error("field '" + k + "' missing");
    return *v;
}

const PyObj& objField(const PyObj& o, const std::string& k) {
    const auto* p = std::get_if<std::shared_ptr<PyObj>>(&field(o, k).v);
    if (!p) throw std::runtime_error("field '" + k + "' is not an object");
    return **p;
}

const std::vector<PyValue>& arrField(const PyObj& o, const std::string& k) {
    const auto* p = std::get_if<std::vector<PyValue>>(&field(o, k).v);
    if (!p) throw std::runtime_error("field '" + k + "' is not an array");
    return *p;
}

std::string strField(const PyObj& o, const std::string& k) {
    const auto* p = std::get_if<std::string>(&field(o, k).v);
    if (!p) throw std::runtime_error("field '" + k + "' is not a string");
    return *p;
}

bool boolField(const PyObj& o, const std::string& k) {
    const auto* p = std::get_if<bool>(&field(o, k).v);
    if (!p) throw std::runtime_error("field '" + k + "' is not a bool");
    return *p;
}

double numFromValue(const PyValue& v) { return pyNumberToFloat(v); }

double numField(const PyObj& o, const std::string& k) { return pyNumberToFloat(field(o, k)); }

// A float that may carry the "nan"/"inf"/"-inf" markers.
double flexFromValue(const PyValue& v) {
    if (const auto* s = std::get_if<std::string>(&v.v)) {
        if (*s == "nan") return std::nan("");
        if (*s == "inf") return HUGE_VAL;
        if (*s == "-inf") return -HUGE_VAL;
        throw std::runtime_error("bad flex marker: " + *s);
    }
    return pyNumberToFloat(v);
}

double flexField(const PyObj& o, const std::string& k) { return flexFromValue(field(o, k)); }

long long intFromValue(const PyValue& v) {
    if (const auto* n = std::get_if<PyNum>(&v.v)) {
        return std::strtoll(n->text.c_str(), nullptr, 10);
    }
    if (const auto* i = std::get_if<long long>(&v.v)) return *i;
    if (const auto* d = std::get_if<double>(&v.v)) return static_cast<long long>(*d);
    throw std::runtime_error("value is not an int");
}

long long intField(const PyObj& o, const std::string& k) { return intFromValue(field(o, k)); }

uint64_t uintFromValue(const PyValue& v) {
    if (const auto* n = std::get_if<PyNum>(&v.v)) {
        return std::strtoull(n->text.c_str(), nullptr, 10);
    }
    if (const auto* i = std::get_if<long long>(&v.v)) return static_cast<uint64_t>(*i);
    throw std::runtime_error("value is not an int");
}

const PyObj& caseObj(const PyValue& v) {
    const auto* p = std::get_if<std::shared_ptr<PyObj>>(&v.v);
    if (!p) throw std::runtime_error("case is not an object");
    return **p;
}

// ---------------------------------------------------------------- comparators

bool bitsEq(double a, double b) {
    if (std::isnan(a) || std::isnan(b)) return std::isnan(a) && std::isnan(b);
    return a == b;
}

// fewUlpEq: relative tolerance covering a handful of ulp of libm divergence.
bool fewUlpEq(double a, double b) {
    if (bitsEq(a, b)) return true;
    if (std::isnan(a) || std::isnan(b) || std::isinf(a) || std::isinf(b)) return false;
    if (b == 0) return std::fabs(a) < 1e-300;
    return std::fabs(a - b) / std::fabs(b) < 4e-15;
}

// pValueEq: tail p-values are 2*(1-cdf), so an erf/betainc error of a few ulp
// at magnitude ~1 lands as an absolute error <= ~1e-15 in p regardless of how
// small p itself is.
bool pValueEq(double a, double b) {
    if (bitsEq(a, b)) return true;
    if (std::isnan(a) || std::isnan(b)) return false;
    double d = std::fabs(a - b);
    return d <= 1e-15 || d / std::fabs(b) < 4e-15;
}

std::string fdesc(double v) { return pyReprFloat(v); }

std::string fmtLL(long long v) { return std::to_string(v); }

// ---------------------------------------------------------------- table

const std::vector<PyValue>& casesOf(const PyObj& table, const std::string& name) {
    const PyValue* s = table.get(name);
    if (!s) throw std::runtime_error("section '" + name + "' missing from reference table");
    const PyObj& sec = caseObj(*s);
    return arrField(sec, "cases");
}

// ---------------------------------------------------------------- z / normal

void testZTwoSided(const PyObj& t) {
    for (size_t i = 0; i < casesOf(t, "z_two_sided").size(); i++) {
        const PyObj& c = caseObj(casesOf(t, "z_two_sided")[i]);
        double alpha = numField(c, "alpha");
        double want = numField(c, "want");
        double got = zTwoSided(alpha);
        if (!fewUlpEq(got, want)) {
            fail("z_two_sided[" + fmtLL(i) + "] alpha=" + fdesc(alpha) + ": got " +
                 fdesc(got) + ", want " + fdesc(want) + " (ulp)");
        }
    }
}

void testNormInvCDF(const PyObj& t) {
    for (size_t i = 0; i < casesOf(t, "norm_inv_cdf").size(); i++) {
        const PyObj& c = caseObj(casesOf(t, "norm_inv_cdf")[i]);
        double p = numField(c, "p");
        double want = numField(c, "want");
        double got = normInvCDF(p);
        if (!fewUlpEq(got, want)) {
            fail("normInvCDF[" + fmtLL(i) + "] p=" + fdesc(p) + ": got " + fdesc(got) +
                 ", want " + fdesc(want) + " (ulp)");
        }
    }
}

void testNormCDF(const PyObj& t) {
    for (size_t i = 0; i < casesOf(t, "norm_cdf").size(); i++) {
        const PyObj& c = caseObj(casesOf(t, "norm_cdf")[i]);
        double x = numField(c, "x");
        double want = numField(c, "want");
        double got = normCDF(x);
        if (!fewUlpEq(got, want)) {
            fail("normCDF[" + fmtLL(i) + "] x=" + fdesc(x) + ": got " + fdesc(got) + ", want " +
                 fdesc(want) + " (ulp)");
        }
    }
}

// ---------------------------------------------------------------- intervals

void testWilson(const PyObj& t) {
    const auto& cases = casesOf(t, "wilson");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        int s = static_cast<int>(intField(c, "s"));
        int n = static_cast<int>(intField(c, "n"));
        double alpha = numField(c, "alpha");
        double low = numField(c, "low");
        double high = numField(c, "high");
        double rootsLow = numField(c, "roots_low");
        double rootsHigh = numField(c, "roots_high");
        Interval w = wilsonInterval(s, n, alpha);
        if (!bitsEq(w.low, low) || !bitsEq(w.high, high)) {
            fail("wilson[" + fmtLL(i) + "] " + fmtLL(s) + "/" + fmtLL(n) + " a=" +
                 fdesc(alpha) + " low: got " + fdesc(w.low) + ", want " + fdesc(low) +
                 " (bits)");
            fail("wilson[" + fmtLL(i) + "] " + fmtLL(s) + "/" + fmtLL(n) + " a=" +
                 fdesc(alpha) + " high: got " + fdesc(w.high) + ", want " + fdesc(high) +
                 " (bits)");
        }
        Interval r = wilsonIntervalRoots(s, n, alpha);
        if (!bitsEq(r.low, rootsLow) || !bitsEq(r.high, rootsHigh)) {
            fail("wilsonRoots[" + fmtLL(i) + "] " + fmtLL(s) + "/" + fmtLL(n) + " a=" +
                 fdesc(alpha) + " low: got " + fdesc(r.low) + ", want " + fdesc(rootsLow) +
                 " (bits)");
            fail("wilsonRoots[" + fmtLL(i) + "] " + fmtLL(s) + "/" + fmtLL(n) + " a=" +
                 fdesc(alpha) + " high: got " + fdesc(r.high) + ", want " + fdesc(rootsHigh) +
                 " (bits)");
        }
    }
}

void testNewcombe(const PyObj& t) {
    const auto& cases = casesOf(t, "newcombe");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        double p1 = numField(c, "p1");
        int n1 = static_cast<int>(intField(c, "n1"));
        double p2 = numField(c, "p2");
        int n2 = static_cast<int>(intField(c, "n2"));
        double alpha = numField(c, "alpha");
        double low = numField(c, "low");
        double high = numField(c, "high");
        Interval got = newcombeDiffInterval(p1, n1, p2, n2, alpha);
        if (!bitsEq(got.low, low) || !bitsEq(got.high, high)) {
            fail("newcombe[" + fmtLL(i) + "]: got low " + fdesc(got.low) + ", want " +
                 fdesc(low) + " (bits)");
            fail("newcombe[" + fmtLL(i) + "]: got high " + fdesc(got.high) + ", want " +
                 fdesc(high) + " (bits)");
        }
    }
}

void testTwoProportion(const PyObj& t) {
    const auto& cases = casesOf(t, "two_prop");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        int s1 = static_cast<int>(intField(c, "s1"));
        int n1 = static_cast<int>(intField(c, "n1"));
        int s2 = static_cast<int>(intField(c, "s2"));
        int n2 = static_cast<int>(intField(c, "n2"));
        double alpha = numField(c, "alpha");
        double diff = numField(c, "diff");
        double low = numField(c, "low");
        double high = numField(c, "high");
        double z = flexField(c, "z");
        double p = flexField(c, "p");
        TwoPropResult r = twoProportionTest(s1, n1, s2, n2, alpha);
        if (!bitsEq(r.diff, diff)) {
            fail("twoProp[" + fmtLL(i) + "] diff: got " + fdesc(r.diff) + ", want " +
                 fdesc(diff) + " (bits)");
        }
        if (!bitsEq(r.ci.low, low) || !bitsEq(r.ci.high, high)) {
            fail("twoProp[" + fmtLL(i) + "] ci.low: got " + fdesc(r.ci.low) + ", want " +
                 fdesc(low) + " (bits)");
            fail("twoProp[" + fmtLL(i) + "] ci.high: got " + fdesc(r.ci.high) + ", want " +
                 fdesc(high) + " (bits)");
        }
        if (!bitsEq(r.z, z)) {
            fail("twoProp[" + fmtLL(i) + "] z: got " + fdesc(r.z) + ", want " + fdesc(z) +
                 " (bits)");
        }
        if (!pValueEq(r.pValue, p)) {
            fail("twoProp[" + fmtLL(i) + "] p: got " + fdesc(r.pValue) + ", want " + fdesc(p) +
                 " (ulp)");
        }
    }
}

void testBinomCDF(const PyObj& t) {
    const auto& cases = casesOf(t, "binom_cdf");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        int k = static_cast<int>(intField(c, "k"));
        int n = static_cast<int>(intField(c, "n"));
        double p = numField(c, "p");
        double want = numField(c, "want");
        double got = binomCDF(k, n, p);
        if (!bitsEq(got, want)) {
            fail("BinomCDF[" + fmtLL(i) + "] k=" + fmtLL(k) + " n=" + fmtLL(n) +
                 " p=" + fdesc(p) + ": got " + fdesc(got) + ", want " + fdesc(want) +
                 " (bits)");
        }
    }
}

void testMcNemar(const PyObj& t) {
    const auto& cases = casesOf(t, "mcnemar");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        int b = static_cast<int>(intField(c, "b"));
        int cc = static_cast<int>(intField(c, "c"));
        double alpha = numField(c, "alpha");
        double diff = numField(c, "diff");
        double low = numField(c, "low");
        double high = numField(c, "high");
        double p = numField(c, "p");
        McNemarResult m = mcnemarExact(b, cc, alpha);
        if (!bitsEq(m.diff, diff) || !bitsEq(m.pValue, p)) {
            fail("mcnemar[" + fmtLL(i) + "] b=" + fmtLL(b) + " c=" + fmtLL(cc) +
                 " diff: got " + fdesc(m.diff) + ", want " + fdesc(diff) + " (bits)");
            fail("mcnemar[" + fmtLL(i) + "] b=" + fmtLL(b) + " c=" + fmtLL(cc) +
                 " p: got " + fdesc(m.pValue) + ", want " + fdesc(p) + " (bits)");
        }
        if (!bitsEq(m.ci.low, low) || !bitsEq(m.ci.high, high)) {
            fail("mcnemar[" + fmtLL(i) + "] b=" + fmtLL(b) + " c=" + fmtLL(cc) +
                 " low: got " + fdesc(m.ci.low) + ", want " + fdesc(low) + " (bits)");
            fail("mcnemar[" + fmtLL(i) + "] b=" + fmtLL(b) + " c=" + fmtLL(cc) +
                 " high: got " + fdesc(m.ci.high) + ", want " + fdesc(high) + " (bits)");
        }
    }
}

void testClusterBootstrap(const PyObj& t) {
    const auto& cases = casesOf(t, "cluster_bootstrap");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        std::vector<std::vector<double>> clusters;
        for (const PyValue& cv : arrField(c, "clusters")) {
            const auto* inner = std::get_if<std::vector<PyValue>>(&cv.v);
            if (!inner) throw std::runtime_error("cluster is not an array");
            std::vector<double> xs;
            xs.reserve(inner->size());
            for (const PyValue& x : *inner) xs.push_back(numFromValue(x));
            clusters.push_back(std::move(xs));
        }
        int B = static_cast<int>(intField(c, "B"));
        double alpha = numField(c, "alpha");
        int seed = static_cast<int>(intField(c, "seed"));
        double low = numField(c, "low");
        double high = numField(c, "high");
        Interval ci = clusterBootstrapCI(clusters, nullptr, B, alpha, seed);
        if (!bitsEq(ci.low, low) || !bitsEq(ci.high, high)) {
            fail("bootstrap[" + fmtLL(i) + "] k=" + fmtLL(clusters.size()) + " B=" + fmtLL(B) +
                 " seed=" + fmtLL(seed) + " low: got " + fdesc(ci.low) + ", want " +
                 fdesc(low) + " (bits)");
            fail("bootstrap[" + fmtLL(i) + "] k=" + fmtLL(clusters.size()) + " B=" + fmtLL(B) +
                 " seed=" + fmtLL(seed) + " high: got " + fdesc(ci.high) + ", want " +
                 fdesc(high) + " (bits)");
        }
    }
}

// ---------------------------------------------------------------- mean / stdev

void testMeanStdev(const PyObj& t) {
    const auto& cases = casesOf(t, "mean_stdev");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        std::vector<double> vals;
        for (const PyValue& v : arrField(c, "vals")) vals.push_back(numFromValue(v));
        double mean = numField(c, "mean");
        double gotMean = exactMean(vals);
        if (!bitsEq(gotMean, mean)) {
            fail("mean[" + fmtLL(i) + "] n=" + fmtLL(vals.size()) + ": got " + fdesc(gotMean) +
                 ", want " + fdesc(mean) + " (bits)");
        }
        const PyValue* sd = c.get("stdev");
        if (sd && sd->v.index() != 0) {  // present and not null
            double want = numFromValue(*sd);
            double got = exactStdev(vals);
            if (!bitsEq(got, want)) {
                fail("stdev[" + fmtLL(i) + "] n=" + fmtLL(vals.size()) + ": got " +
                     fdesc(got) + ", want " + fdesc(want) + " (bits)");
            }
        }
    }
}

// ---------------------------------------------------------------- power

void testPower(const PyObj& t) {
    const auto& cases = casesOf(t, "power");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        std::string kind = strField(c, "kind");
        // Cases only carry the fields relevant to their kind.
        auto opt = [&](const char* k) -> double {
            const PyValue* v = c.get(k);
            return v ? pyNumberToFloat(*v) : 0.0;
        };
        double p1 = opt("p1");
        double p2 = opt("p2");
        double disc = opt("disc");
        double delta = opt("delta");
        double width = opt("width");
        double p = opt("p");
        double alpha = opt("alpha");
        double power = opt("power");
        int want = static_cast<int>(intField(c, "n"));
        int got = 0;
        if (kind == "two") {
            got = nTwoProportions(p1, p2, alpha, power).nPerVersion;
        } else if (kind == "paired") {
            got = nPaired(disc, delta, alpha, power).nPerVersion;
        } else if (kind == "width") {
            got = nForCIWidth(width, p, alpha).nPerVersion;
        } else {
            throw std::runtime_error("power[" + fmtLL(i) + "]: unknown kind '" + kind + "'");
        }
        if (got != want) {
            fail("power[" + fmtLL(i) + "] " + kind + ": got n=" + fmtLL(got) + ", want " +
                 fmtLL(want));
        }
    }
}

// ---------------------------------------------------------------- variance

void testVarianceComponents(const PyObj& t) {
    const auto& cases = casesOf(t, "variance_components");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        std::vector<std::unique_ptr<Group>> owned;
        std::vector<const Group*> groups;
        for (const PyValue& gv : arrField(c, "groups")) {
            const auto* pair = std::get_if<std::vector<PyValue>>(&gv.v);
            if (!pair || pair->size() != 2) {
                throw std::runtime_error("variance[" + fmtLL(i) + "]: bad group");
            }
            const auto* name = std::get_if<std::string>(&(*pair)[0].v);
            const auto* valsArr = std::get_if<std::vector<PyValue>>(&(*pair)[1].v);
            if (!name || !valsArr) {
                throw std::runtime_error("variance[" + fmtLL(i) + "]: bad group shape");
            }
            auto g = std::make_unique<Group>();
            g->key = *name;
            g->vals.reserve(valsArr->size());
            for (const PyValue& x : *valsArr) g->vals.push_back(numFromValue(x));
            groups.push_back(g.get());
            owned.push_back(std::move(g));
        }
        double between = numField(c, "between");
        double within = numField(c, "within");
        double total = numField(c, "total");
        double icc = numField(c, "icc");
        VarianceComponents vc = varianceComponentsOf(groups);
        if (!bitsEq(vc.between, between) || !bitsEq(vc.within, within) ||
            !bitsEq(vc.total, total) || !bitsEq(vc.icc, icc)) {
            fail("variance[" + fmtLL(i) + "] between: got " + fdesc(vc.between) + ", want " +
                 fdesc(between) + " (bits)");
            fail("variance[" + fmtLL(i) + "] within: got " + fdesc(vc.within) + ", want " +
                 fdesc(within) + " (bits)");
            fail("variance[" + fmtLL(i) + "] total: got " + fdesc(vc.total) + ", want " +
                 fdesc(total) + " (bits)");
            fail("variance[" + fmtLL(i) + "] icc: got " + fdesc(vc.icc) + ", want " +
                 fdesc(icc) + " (bits)");
        }
    }
}

// ---------------------------------------------------------------- holm

void testHolm(const PyObj& t) {
    const auto& cases = casesOf(t, "holm");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        double alpha = numField(c, "alpha");
        std::vector<HolmP> in;
        for (const PyValue& e : arrField(c, "entries")) {
            const auto* pair = std::get_if<std::vector<PyValue>>(&e.v);
            if (!pair || pair->size() != 2) {
                throw std::runtime_error("holm[" + fmtLL(i) + "]: bad entry");
            }
            HolmP hp;
            if (const auto* s = std::get_if<std::string>(&(*pair)[0].v)) {
                hp.name = *s;
            } else {
                hp.name = pyStr((*pair)[0]);
            }
            hp.p = numFromValue((*pair)[1]);
            in.push_back(hp);
        }
        std::vector<HolmEntry> got = holm(std::move(in), alpha);
        const auto& want = arrField(c, "want");
        if (got.size() != want.size()) {
            fail("holm[" + fmtLL(i) + "]: got " + fmtLL(got.size()) + " entries, want " +
                 fmtLL(want.size()));
            continue;
        }
        for (size_t j = 0; j < want.size(); j++) {
            const auto* w = std::get_if<std::vector<PyValue>>(&want[j].v);
            if (!w || w->size() != 3) throw std::runtime_error("holm: bad want row");
            std::string wantName = pyStr((*w)[0]);
            double wantAdj = numFromValue((*w)[1]);
            bool wantReject = false;
            if (const auto* b = std::get_if<bool>(&(*w)[2].v)) wantReject = *b;
            if (got[j].name != wantName) {
                fail("holm[" + fmtLL(i) + "][" + fmtLL(j) + "]: name got '" + got[j].name +
                     "' want '" + wantName + "'");
            }
            if (!bitsEq(got[j].adjusted, wantAdj)) {
                fail("holm[" + fmtLL(i) + "][" + fmtLL(j) + "] adj: got " +
                     fdesc(got[j].adjusted) + ", want " + fdesc(wantAdj) + " (bits)");
            }
            if (got[j].reject != wantReject) {
                fail("holm[" + fmtLL(i) + "][" + fmtLL(j) + "]: reject got " +
                     (got[j].reject ? "true" : "false") + " want " +
                     (wantReject ? "true" : "false"));
            }
        }
    }
}

// ---------------------------------------------------------------- MT19937

void testMT19937(const PyObj& t) {
    const auto& cases = casesOf(t, "mt19937");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        long long seed = intField(c, "seed");
        std::string kind = strField(c, "kind");
        long long k = 0;
        if (const PyValue* kv = c.get("k")) k = intFromValue(*kv);
        const auto& want = arrField(c, "want");
        PyRandom r;
        r.seedInt(seed);
        std::vector<uint64_t> got;
        if (kind == "randrange") {
            for (size_t j = 0; j < want.size(); j++) {
                got.push_back(static_cast<uint64_t>(r.randrange(static_cast<int>(k))));
            }
        } else if (kind == "getrandbits32") {
            for (size_t j = 0; j < want.size(); j++) got.push_back(r.getrandbits(32));
        } else if (kind.rfind("getrandbits", 0) == 0) {
            int bits = std::atoi(kind.c_str() + std::strlen("getrandbits"));
            for (size_t j = 0; j < want.size(); j++) got.push_back(r.getrandbits(bits));
        } else {
            throw std::runtime_error("mt[" + fmtLL(i) + "]: bad kind '" + kind + "'");
        }
        if (got.size() != want.size()) {
            fail("mt[" + fmtLL(i) + "]: length " + fmtLL(got.size()) + " != " +
                 fmtLL(want.size()));
            continue;
        }
        for (size_t j = 0; j < got.size(); j++) {
            uint64_t wantV = uintFromValue(want[j]);
            if (got[j] != wantV) {
                fail("mt[" + fmtLL(i) + "] " + kind + " seed=" + fmtLL(seed) + " [" +
                     fmtLL(j) + "]: got " + std::to_string(got[j]) + ", want " +
                     std::to_string(wantV));
            }
        }
    }
}

// ---------------------------------------------------------------- formatting

void testPyRound(const PyObj& t) {
    const auto& cases = casesOf(t, "py_round");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        double x = numField(c, "x");
        long long want = intField(c, "want");
        long long got = pyRound(x);
        if (got != want) {
            fail("pyRound[" + fmtLL(i) + "] x=" + fdesc(x) + ": got " + fmtLL(got) +
                 ", want " + fmtLL(want));
        }
    }
}

void testFmt(const PyObj& t, const std::string& section,
             const std::function<std::string(double)>& fn) {
    const auto& cases = casesOf(t, section);
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        double x = numField(c, "x");
        std::string want = strField(c, "want");
        std::string got = fn(x);
        if (got != want) {
            fail(section + "[" + fmtLL(i) + "] x=" + fdesc(x) + ": got \"" + got +
                 "\", want \"" + want + "\"");
        }
    }
}

void testJSONDumps(const PyObj& t) {
    const auto& cases = casesOf(t, "json_dumps");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        std::string got = pyJSONDumps(field(c, "value"));
        std::string want = strField(c, "want");
        if (got != want) {
            fail("jsonDumps[" + fmtLL(i) + "]:\ngot  \"" + got + "\"\nwant \"" + want + "\"");
        }
    }
}

// ---------------------------------------------------------------- compare

std::vector<Run> runsFromValue(const PyValue& v) {
    const auto* arr = std::get_if<std::vector<PyValue>>(&v.v);
    if (!arr) throw std::runtime_error("expected array of runs");
    return runsFromArray(*arr, "");
}

void testCompare(const PyObj& t) {
    const auto& cases = casesOf(t, "compare");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        std::string name = strField(c, "name");
        double alpha = numField(c, "alpha");
        std::vector<Run> ra = runsFromValue(field(c, "runs_a"));
        std::vector<Run> rb = runsFromValue(field(c, "runs_b"));
        const PyObj& w = objField(c, "want");
        Comparison got = compare(ra, rb, "A", "B", alpha);
        double wantEst = flexField(w, "estimate");
        double wantLow = flexField(w, "low");
        double wantHigh = flexField(w, "high");
        double wantP = flexField(w, "p");
        std::string wantMethod = strField(w, "method");
        bool wantPaired = boolField(w, "paired");
        std::string wantVerdict = strField(w, "verdict");
        int wantNeeded = static_cast<int>(intField(w, "additional_needed"));
        if (!bitsEq(got.estimate, wantEst)) {
            fail("compare[" + fmtLL(i) + "] " + name + " estimate: got " + fdesc(got.estimate) +
                 ", want " + fdesc(wantEst) + " (bits)");
        }
        if (!bitsEq(got.ci.low, wantLow) || !bitsEq(got.ci.high, wantHigh)) {
            fail("compare[" + fmtLL(i) + "] " + name + " ci.low: got " + fdesc(got.ci.low) +
                 ", want " + fdesc(wantLow) + " (bits)");
            fail("compare[" + fmtLL(i) + "] " + name + " ci.high: got " + fdesc(got.ci.high) +
                 ", want " + fdesc(wantHigh) + " (bits)");
        }
        if (!pValueEq(got.pValue, wantP)) {
            fail("compare[" + fmtLL(i) + "] " + name + " p: got " + fdesc(got.pValue) +
                 ", want " + fdesc(wantP) + " (ulp)");
        }
        if (got.method != wantMethod || got.paired != wantPaired || got.verdict != wantVerdict ||
            got.additionalNeeded != wantNeeded) {
            fail("compare[" + fmtLL(i) + "] " + name + ": method='" + got.method +
                 "' paired=" + (got.paired ? "true" : "false") + " verdict='" + got.verdict +
                 "' needed=" + fmtLL(got.additionalNeeded) + "; want '" + wantMethod + "' " +
                 (wantPaired ? "true" : "false") + " '" + wantVerdict + "' " +
                 fmtLL(wantNeeded));
        }
    }
}

// ---------------------------------------------------------------- decide

void testDecide(const PyObj& t) {
    const auto& cases = casesOf(t, "decide");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        const PyObj& candObj = objField(c, "candidates");
        double alpha = numField(c, "alpha");
        std::vector<Candidate> cands;
        for (const auto& kv : candObj.pairs) {
            Candidate cand;
            cand.name = kv.first;
            cand.runs = runsFromValue(kv.second);
            cands.push_back(std::move(cand));
        }
        DecisionReport rep = decide(cands, alpha);
        const auto& wantRanking = arrField(c, "want_ranking");
        const auto& wantAdjusted = arrField(c, "want_adjusted");
        const auto& wantVerdicts = arrField(c, "want_verdicts");
        const auto& wantMethods = arrField(c, "want_methods");
        for (size_t j = 0; j < wantRanking.size(); j++) {
            const auto* w = std::get_if<std::vector<PyValue>>(&wantRanking[j].v);
            if (!w || w->size() != 3) throw std::runtime_error("decide: bad ranking row");
            std::string name = pyStr((*w)[0]);
            double wantEst = numFromValue((*w)[1]);
            std::string wantAction = pyStr((*w)[2]);
            if (rep.ranking[j].name != name) {
                fail("decide[" + fmtLL(i) + "] ranking[" + fmtLL(j) + "]: name got '" +
                     rep.ranking[j].name + "' want '" + name + "'");
            }
            if (!bitsEq(rep.ranking[j].estimate, wantEst)) {
                fail("decide[" + fmtLL(i) + "] ranking[" + fmtLL(j) + "] " + name +
                     " est: got " + fdesc(rep.ranking[j].estimate) + ", want " +
                     fdesc(wantEst) + " (bits)");
            }
            if (rep.ranking[j].action != wantAction) {
                fail("decide[" + fmtLL(i) + "] ranking[" + fmtLL(j) + "] " + name +
                     ": action got '" + rep.ranking[j].action + "' want '" + wantAction + "'");
            }
        }
        for (size_t j = 0; j < wantAdjusted.size(); j++) {
            const auto* w = std::get_if<std::vector<PyValue>>(&wantAdjusted[j].v);
            if (!w || w->size() != 2) throw std::runtime_error("decide: bad adjusted row");
            // w[1] is Python's repr of the adjusted p — compare via repr
            std::string wantName = pyStr((*w)[0]);
            std::string wantRepr = pyStr((*w)[1]);
            if (rep.adjusted[j].name != wantName ||
                pyReprFloat(rep.adjusted[j].adjusted) != wantRepr) {
                fail("decide[" + fmtLL(i) + "] adjusted[" + fmtLL(j) + "]: got '" +
                     rep.adjusted[j].name + "' " + pyReprFloat(rep.adjusted[j].adjusted) +
                     ", want '" + wantName + "' " + wantRepr);
            }
        }
        if (rep.comparisons.size() != wantVerdicts.size()) {
            fail("decide[" + fmtLL(i) + "]: " + fmtLL(rep.comparisons.size()) +
                 " comparisons, want " + fmtLL(wantVerdicts.size()));
            continue;
        }
        for (size_t j = 0; j < rep.comparisons.size(); j++) {
            std::string wantVerdict = pyStr(wantVerdicts[j]);
            std::string wantMethod = pyStr(wantMethods[j]);
            if (rep.comparisons[j].verdict != wantVerdict ||
                rep.comparisons[j].method != wantMethod) {
                fail("decide[" + fmtLL(i) + "] comparison[" + fmtLL(j) + "]: verdict='" +
                     rep.comparisons[j].verdict + "' method='" + rep.comparisons[j].method +
                     "'; want '" + wantVerdict + "' '" + wantMethod + "'");
            }
        }
    }
}

// ---------------------------------------------------------------- sequential

void testSequential(const PyObj& t) {
    const auto& cases = casesOf(t, "sequential");
    for (size_t i = 0; i < cases.size(); i++) {
        const PyObj& c = caseObj(cases[i]);
        std::string kind = strField(c, "kind");
        double alpha = numField(c, "alpha");
        double half = numField(c, "half");
        const auto& steps = arrField(c, "steps");
        const auto& verdicts = arrField(c, "verdicts");
        int looksUsedWant = static_cast<int>(intField(c, "looks_used"));
        if (steps.size() != verdicts.size()) {
            fail("sequential[" + fmtLL(i) + "]: steps/verdicts length mismatch");
            continue;
        }
        if (kind == "prop") {
            SequentialProportion sp(alpha, half);
            for (size_t j = 0; j < steps.size(); j++) {
                const auto* st = std::get_if<std::vector<PyValue>>(&steps[j].v);
                if (!st || st->size() < 2) throw std::runtime_error("bad step");
                std::string want = pyStr(verdicts[j]);
                std::string got = sp.update(static_cast<int>(intFromValue((*st)[0])),
                                            static_cast<int>(intFromValue((*st)[1])));
                if (got != want) {
                    fail("sequential[" + fmtLL(i) + "] step " + fmtLL(j) + ": verdict got '" +
                         got + "' want '" + want + "'");
                }
            }
            if (sp.looksUsed != looksUsedWant) {
                fail("sequential[" + fmtLL(i) + "]: looks_used got " + fmtLL(sp.looksUsed) +
                     " want " + fmtLL(looksUsedWant));
            }
        } else {
            SequentialAB ab(alpha, half);
            for (size_t j = 0; j < steps.size(); j++) {
                const auto* st = std::get_if<std::vector<PyValue>>(&steps[j].v);
                if (!st || st->size() < 4) throw std::runtime_error("bad step");
                std::string want = pyStr(verdicts[j]);
                std::string got = ab.update(static_cast<int>(intFromValue((*st)[0])),
                                            static_cast<int>(intFromValue((*st)[1])),
                                            static_cast<int>(intFromValue((*st)[2])),
                                            static_cast<int>(intFromValue((*st)[3])));
                if (got != want) {
                    fail("sequential[" + fmtLL(i) + "] step " + fmtLL(j) + ": verdict got '" +
                         got + "' want '" + want + "'");
                }
            }
            if (ab.looksUsed != looksUsedWant) {
                fail("sequential[" + fmtLL(i) + "]: looks_used got " + fmtLL(ab.looksUsed) +
                     " want " + fmtLL(looksUsedWant));
            }
        }
    }
}

// ---------------------------------------------------------------- error parity

// The Python reference raises StatisticsError when every cluster in a
// bootstrap resample is empty; the Go port panics with the same message. With
// k=2 clusters of which one is empty, a quarter of seeds hit the all-empty
// resample, so this pins the error path too.
void testClusterBootstrapAllEmptyResampleThrows() {
    std::vector<std::vector<double>> clusters = {{1.0, 2.0}, {}};
    bool threw = false;
    try {
        clusterBootstrapCI(clusters, nullptr, 4, 0.05, 0);
    } catch (const std::exception&) {
        threw = true;
    }
    if (!threw) fail("expected throw on all-empty resample");
}

// The Python reference raises ValueError("n must be >= 1, ...") on zero sample
// size; the ports throw with the same message instead of dividing to NaN.
void testZeroNThrows() {
    struct TC {
        std::string name;
        std::function<void()> fn;
    };
    std::vector<TC> tcs = {
        {"two_proportion n1=0", [] { twoProportionTest(0, 0, 5, 10, 0.05); }},
        {"two_proportion n2=0", [] { twoProportionTest(5, 10, 0, 0, 0.05); }},
        {"sequential update n=0", [] { SequentialProportion(0.05, 0.05).update(0, 0); }},
    };
    for (const auto& tc : tcs) {
        bool threw = false;
        std::string msg;
        try {
            tc.fn();
        } catch (const std::exception& e) {
            threw = true;
            msg = e.what();
        }
        if (!threw) {
            fail(tc.name + ": expected throw, got none");
        } else if (msg != "n must be >= 1, got 0") {
            fail(tc.name + ": message got \"" + msg + "\", want \"n must be >= 1, got 0\"");
        }
    }
}

}  // namespace

int main() {
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    std::string data;
    std::string usedPath;
    for (const std::string& p : REFDATA_PATHS) {
        std::ifstream f(p, std::ios::binary);
        if (f) {
            std::ostringstream ss;
            ss << f.rdbuf();
            data = ss.str();
            usedPath = p;
            break;
        }
    }
    if (data.empty()) {
        std::fprintf(stderr,
                     "reference table not found: %s (run tests/gen_ref_tables.py)\n",
                     REFDATA_PATHS[0].c_str());
        return 2;
    }
    PyValue root;
    try {
        root = parsePyJSON(data);
    } catch (const std::exception& e) {
        std::fprintf(stderr, "bad reference table: %s\n", e.what());
        return 2;
    }
    const PyObj* table = std::get_if<std::shared_ptr<PyObj>>(&root.v) == nullptr
                             ? nullptr
                             : std::get<std::shared_ptr<PyObj>>(root.v).get();
    if (!table) {
        std::fprintf(stderr, "reference table is not a JSON object\n");
        return 2;
    }

    struct Section {
        const char* name;
        void (*fn)(const PyObj&);
    };
    std::vector<Section> sections = {
        {"z_two_sided", testZTwoSided},
        {"norm_inv_cdf", testNormInvCDF},
        {"norm_cdf", testNormCDF},
        {"wilson", testWilson},
        {"newcombe", testNewcombe},
        {"two_prop", testTwoProportion},
        {"binom_cdf", testBinomCDF},
        {"mcnemar", testMcNemar},
        {"cluster_bootstrap", testClusterBootstrap},
        {"mean_stdev", testMeanStdev},
        {"power", testPower},
        {"variance_components", testVarianceComponents},
        {"holm", testHolm},
        {"mt19937", testMT19937},
        {"py_round", testPyRound},
        {"json_dumps", testJSONDumps},
        {"compare", testCompare},
        {"decide", testDecide},
        {"sequential", testSequential},
    };

    for (const Section& s : sections) {
        int before = g_failures;
        auto t0 = std::chrono::steady_clock::now();
        try {
            s.fn(*table);
        } catch (const std::exception& e) {
            fail(std::string(s.name) + ": fatal: " + e.what());
        }
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                      std::chrono::steady_clock::now() - t0)
                      .count();
        std::printf("%-24s %-4s %lldms\n", s.name, g_failures == before ? "ok" : "FAIL",
                    static_cast<long long>(ms));
        g_sections++;
    }

    // text-format sections
    {
        int before = g_failures;
        try {
            testFmt(*table, "fmt_g4", [](double x) { return pyFormatG(x, 4); });
            testFmt(*table, "fmt_f4", [](double x) { return pyFormatF(x, 4); });
            testFmt(*table, "fmt_pct", [](double x) { return pyPercent0(x); });
            testFmt(*table, "py_repr", [](double x) { return pyReprFloat(x); });
        } catch (const std::exception& e) {
            fail(std::string("fmt: fatal: ") + e.what());
        }
        std::printf("%-24s %s\n", "fmt_g4/f4/pct/repr", g_failures == before ? "ok" : "FAIL");
        g_sections++;
    }

    {
        int before = g_failures;
        try {
            testClusterBootstrapAllEmptyResampleThrows();
            testZeroNThrows();
        } catch (const std::exception& e) {
            fail(std::string("error-parity: fatal: ") + e.what());
        }
        std::printf("%-24s %s\n", "error-parity", g_failures == before ? "ok" : "FAIL");
        g_sections++;
    }

    if (g_failures > 0) {
        std::printf("\nFAIL  %d failure(s) over %d sections (%s)\n", g_failures, g_sections,
                    usedPath.c_str());
        return 1;
    }
    std::printf("\nok    %d sections, all cases pass (%s)\n", g_sections, usedPath.c_str());
    return 0;
}
